---
namespace: "zloveless"
name: "containers"
description: ""
version: "1.1.2"
readme: "README.md"
authors:
  - "Zack Loveless (https://zloveless.com)"
license_file: "LICENSE"
repository: "https://github.com/zloveless/ansible-containers"
dependencies:
  "community.docker": ">=1.7.0"
